# Generated by Django 3.2.7 on 2023-09-09 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='Name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default=datetime.datetime(2023, 9, 9, 23, 55, 36, 904098), max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 23, 55, 36, 904098), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 23, 55, 36, 905097), editable=False),
        ),
    ]
