# Generated by Django 3.2.7 on 2023-09-12 06:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0003_auto_20230910_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Products', models.CharField(default='Anonymous', max_length=200)),
                ('Price', models.CharField(max_length=50)),
                ('NoOfStock', models.CharField(max_length=50)),
                ('Date_Pub', models.DateTimeField(default=datetime.datetime(2023, 9, 12, 7, 55, 24, 184537), editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Women', 'Women')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 7, 55, 24, 183537), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 7, 55, 24, 184537), editable=False),
        ),
    ]
