# Generated by Django 3.2.7 on 2023-09-12 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0004_auto_20230912_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 18, 25, 672376), editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='NoOfStock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 18, 25, 671376), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 18, 25, 673375), editable=False),
        ),
    ]
