# Generated by Django 3.2.7 on 2023-09-12 07:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0005_auto_20230912_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 12, 8, 43, 22, 81942), editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Products',
            field=models.CharField(blank=True, default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='uniqueID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Kids', 'Kids'), ('Women', 'Women')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 43, 22, 73911), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 43, 22, 81942), editable=False),
        ),
    ]
