# Generated by Django 3.2.7 on 2023-09-12 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0007_auto_20230912_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ClientEmail',
            field=models.CharField(blank=True, default='Anonymous@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='MobileNo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentOption',
            field=models.CharField(blank=True, choices=[('Pay on delivery', 'Pay on delivery'), ('Instant payment', 'Inatant payment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 12, 19, 40, 12, 445200), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 19, 40, 12, 445200), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 19, 40, 12, 446201), editable=False),
        ),
    ]
