# Generated by Django 3.2.7 on 2023-09-12 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0008_auto_20230912_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentOption', models.CharField(blank=True, choices=[('Pay on delivery', 'Pay on delivery'), ('Instant payment', 'Inatant payment')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 12, 19, 54, 38, 553786), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 19, 54, 38, 552786), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 19, 54, 38, 554787), editable=False),
        ),
    ]
