# Generated by Django 3.2.7 on 2023-09-13 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0009_auto_20230912_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=50)),
                ('Availability', models.CharField(choices=[('Yes I will be available', 'Yes I will be available'), ("No I won't", "No I won't")], max_length=30)),
                ('Skills', models.TextField(max_length=500)),
                ('Role', models.CharField(choices=[('Venue Management', 'Venue Management'), ('Marketing and Communication', 'Marketing and Communication'), ('Logistics and Operations team', 'Logistics and Operations team'), ('Security Personnels/team', 'Security Personnels/team'), ('Public Relations', 'Public Relations'), ('Technology and Media team', 'Technology and Media team'), ("Speaker's Relations", "Speaker's Relations"), ('Partnership and Sponsorship team', 'Partnership and Sponsorship team'), ('Programme Management team', 'Programme Management team'), ('Hospitality team', 'Hospitality team')], max_length=50)),
                ('Experirence', models.TextField()),
                ('Motivation', models.TextField()),
                ('Expectations', models.CharField(max_length=200)),
                ('ShirtSize', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 13, 20, 11, 37, 701782), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Women', 'Women')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 20, 11, 37, 701782), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 20, 11, 37, 702783), editable=False),
        ),
    ]
