# Generated by Django 3.2.7 on 2023-09-15 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0010_auto_20230913_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunter',
        ),
        migrations.AddField(
            model_name='order',
            name='Country',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='Delivery_Adress',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='LGA',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='Zip_Code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_Pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 15, 6, 57, 53, 785689), editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='PaymentOption',
            field=models.CharField(blank=True, choices=[('Instant payment', 'Inatant payment'), ('Pay on delivery', 'Pay on delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 6, 57, 53, 784688), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 6, 57, 53, 786686), editable=False),
        ),
    ]
